---
- name: Create grafana data dir
  file:
    path: "{{ grafana_storage_location }}"
    state: directory
    owner: 472
    mode: 0755

- name: Save stack file
  template:
    src: stack-grafana.yml
    dest: "{{ monitor_stack_files_dest_dir }}/stack-grafana.yml"
    mode: 0644

- name: Deploy stack
  shell: "docker stack deploy -c stack-grafana.yml grafana"
  args:
    chdir: "{{ monitor_stack_files_dest_dir }}"
