- hosts: prometheus
  become: yes
  vars:
    grafana_admin_password: changethepassword
  pre_tasks:
    - name: Making docker stac/conf dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - /home/deployer/config
        - /home/deployer/stack
  roles:
    - prometheus
    - grafana

- hosts: vm-node-exporter
  become: yes
  roles:
    - vm-agents-nodeexporter
