- name: Install Ansible Prereqs
  hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
    - raw: bash -c "test -e /usr/bin/python" || (apt install python-minimal -y)

- name: Install Docker
  hosts: swarm-nodes
  become: yes
  roles:
    - docker-ce

- name: Initialize Swarm Master
  hosts: swarm-manager
  gather_facts: false
  become: yes
  tasks:
    - shell: docker info
      changed_when: False
      register: docker_info
    - shell: "docker swarm init --advertise-addr $(hostname -i)"
      when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Create network on manager
  hosts: swarm-nodes:swarm-manager
  gather_facts: false
  become: yes
  gather_facts: yes
  roles: 
    - bootstrap_swarm
